### ISSUE TITLE
News Widget - Single item settings - a bug in Auto-generated page (with the same layout as the list page)

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-widgets#1253] opened 2015-06-09 20:58 UTC
News Widget >> Single item settings >> Open single item in ,,  Auto-generated page (with the same layout as the list page).

I have a page template (including search widget) for list page which inherits a parent page template (a placeholder for search widget). When I selected auto-generated page, it displays parent page layout instead of the same layout as the list page. 

The search widget displays in the news list page. I don't see the search widget in the single news item page. 

Thanks,

Richard

**Comment by PepiIvanova** [comment] 2015-06-10 09:05
Hi Richard,

We cannot reproduce the described behavior with the latest version. The issue is fixed in version v.1.2.160.0: https://github.com/Sitefinity/feather-widgets/commit/55bf02d6ae29ca14fbc138446598c0040acbedd5
So, what version of Feather are you using?

Best,
Pepi

**Comment by rlee2015** [comment] 2015-06-10 12:37
Hi Pepi,

We are using v.1.2.240.0. The issue is not in the search box widget. The issue is in auto-generated page loading the wrong page layout.

Let me describe how we created the page templates. We are using one domain to host multiple web sites and multi languages (i.e. http://domain.com/countrycode, http://domain.com/countrycode/languagecode).

1. Create a new web site called 'SiteB'..
2. Create a generic page template (i.e. global nav, local nav, footer and etc.) called 'TemplateA' in our default site called 'SiteA' and share with the 'TemplateA' in 'SiteB'.
3. Create a new page template called 'TemplateB' in 'SiteB' using 'TemplateA' template.
4. Drag & Drop a search box widget in 'TemplateB' in 'SiteB'.
5. Create a new page called 'PageB' using 'TemplateB' in 'SiteB'.
6. Drag & Drop a news widget in 'PageB' and config the following settings

**Comment by PepiIvanova** [comment] 2015-06-12 09:53
Hi Richard,

Unfortunately, our QAs still cannot reproduce the described issue. Could you try to use Content block instead of Search box in TemplateB? Any details that can help figure out what's wrong are welcome.

Thanks,
Pepi

**Comment by rlee2015** [comment] 2015-06-12 13:53
I submitted a support ticket #943839 to include detail screenshots.

**Comment by rlee2015** [comment] 2015-06-23 12:37
The issue has been solved by adding the following codes in the controller. You can close this ticket. Thanks.

protected override void HandleUnknownAction(string actionName)
 {
 this.Index().ExecuteResult(this.ControllerContext);
 }

**Closed** 2015-06-26 14:11 UTC
Labels: customer submitted
