### ISSUE TITLE
Download List doesn't seem to show icons until you open edit mode

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#1401] opened 2015-08-31 21:36 UTC
http://screencast.com/t/eleBzrD8E5X

Thoughts?  I seem to have the latest version and template...

**Comment by ElenaGaneva** [comment] 2018-11-28 15:48
Hello Steve, 

I can't reproduce this issue in versions 11.1+, so I am going to close this item. 

If you still see this behavior please submit it in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.

**Closed by ElenaGaneva** 2018-11-28 15:48 UTC
